minimum_pre_commit_version: "4.3.0"

repos:
  - repo: local
    hooks:
      - id: format-toml
        name: Format TOML
        entry: npx tombi format --offline --quiet
        language: system
        files: ^data/(character|sect|themes)/.*\.toml$
        types: [toml]
